-- MySQL Script generated by MySQL Workbench
-- Fri May  4 20:57:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table `mydb`.`lrv_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrv_users` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  `name` VARCHAR(90) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(90) NOT NULL,
  `image` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `remember_token` VARCHAR(90) NOT NULL,
  constraint pk_users PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lrv_videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrv_videos` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `user_id` INT(255) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `status` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NULL,
  `video_path` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `lrv_users_id` INT NOT NULL,
  constraint pk_videos PRIMARY KEY (`id`),
  INDEX `fk_lrv_videos_lrv_users_idx` (`lrv_users_id` ASC),
  CONSTRAINT `fk_lrv_videos_lrv_users`
    FOREIGN KEY (`lrv_users_id`)
    REFERENCES `lrv_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lrv_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lrv_comments` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `user_id` INT(255) NOT NULL,
  `video_id` INT(255) NOT NULL,
  `body` VARCHAR(512) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `lrv_users_id` INT NOT NULL,
  `lrv_videos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lrv_comments_lrv_users`
    FOREIGN KEY (`lrv_users_id`)
    REFERENCES `lrv_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lrv_comments_lrv_videos`
    FOREIGN KEY (`lrv_videos_id`)
    REFERENCES `lrv_videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
